// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqNfaTWlT5eNsD2FjeV8Vs2C3ecGHf7YI',
    appId: '1:77053154385:web:8a3b59d604319939599470',
    messagingSenderId: '77053154385',
    projectId: 'app-de-salud-69bf7',
    authDomain: 'app-de-salud-69bf7.firebaseapp.com',
    storageBucket: 'app-de-salud-69bf7.firebasestorage.app',
    measurementId: 'G-9H9L2PH34S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqGRHtV_2N1x704DSy5OlqM8qn9MNY6WU',
    appId: '1:77053154385:android:e361df565e23ea60599470',
    messagingSenderId: '77053154385',
    projectId: 'app-de-salud-69bf7',
    storageBucket: 'app-de-salud-69bf7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYhvhbMNM3WjdYclFAx5QJN0Ww7MeGbpk',
    appId: '1:77053154385:ios:59f872515b67f819599470',
    messagingSenderId: '77053154385',
    projectId: 'app-de-salud-69bf7',
    storageBucket: 'app-de-salud-69bf7.firebasestorage.app',
    iosBundleId: 'com.example.miApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYhvhbMNM3WjdYclFAx5QJN0Ww7MeGbpk',
    appId: '1:77053154385:ios:59f872515b67f819599470',
    messagingSenderId: '77053154385',
    projectId: 'app-de-salud-69bf7',
    storageBucket: 'app-de-salud-69bf7.firebasestorage.app',
    iosBundleId: 'com.example.miApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqNfaTWlT5eNsD2FjeV8Vs2C3ecGHf7YI',
    appId: '1:77053154385:web:eea02f84c0af41d9599470',
    messagingSenderId: '77053154385',
    projectId: 'app-de-salud-69bf7',
    authDomain: 'app-de-salud-69bf7.firebaseapp.com',
    storageBucket: 'app-de-salud-69bf7.firebasestorage.app',
    measurementId: 'G-EDF8DPR0Y8',
  );
}
